//! Mots de la saisie rapide, par langue (hors chinois et japonais, voir `cjk`).
//!
//! Chaque langue liste ses formes (déclinaisons, abréviations, locutions de
//! plusieurs mots) pour des sens communs, que la grammaire de `super` combine.
//! Les formes sont comparées sans casse ni accents (`fold`) : « manana »
//! vaut « mañana ».
//!
//! Actives : l'anglais, le français et le russe (alphabet sans ambiguïté avec
//! les autres), plus la langue de l'interface. Mélanger toutes les langues à
//! alphabet latin créerait des faux positifs : l'espagnol « 2 o 3 manzanas »
//! deviendrait « à 3 h » avec la règle polonaise « o 9 ».

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use chrono::Weekday::{self, *};

use super::fold;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Unit {
    Day,
    Week,
    Month,
    Year,
    Hour,
    Minute,
}

/// Sens d'une forme.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum W {
    Today,
    Tomorrow,
    AfterTomorrow,
    /// Ce soir : aujourd'hui, 19 h par défaut.
    Tonight,
    ThisWeekend,
    NextWeek,
    NextMonth,
    /// Avant un jour : « next », « nächsten », « próximo ».
    Next,
    /// Après un jour : « prochain », « prossimo », « que viene ».
    NextAfter,
    /// Avant un délai : « dans », « in », « tra », « через », « za ».
    In,
    Unit(Unit),
    Number(u32),
    Weekday(Weekday),
    /// Jour abrégé ambigu (portugais « segunda » : lundi ou « deuxième ») :
    /// reconnu seulement après un mot qui annonce un jour.
    WeakWeekday(Weekday),
    /// Habitude : « montags », « los lunes », « по понедельникам », « mondays ».
    Habitual(Weekday),
    Month(u32),
    /// Avant une date ou une heure : « le », « on », « am », « el », « в ».
    Connector,
    /// Avant une heure donnée sans unité : « at 9 », « um 9 », « a las 9 ».
    At,
    /// Après l'heure : « Uhr », « часов », « horas ».
    HourWord,
    Noon,
    Midnight,
    Am,
    Pm,
    /// Après l'heure : « y media », « e mezza », « e meia ».
    Half,
    /// « every », « chaque », « tous les », « jeden », « cada », « каждый », « co ».
    Every,
    /// « every other week » : un sur deux.
    Other,
    Daily,
    Weekly,
    Monthly,
    Yearly,
    WeekdaysOnly,
    /// Jour ouvré comme unité : « every weekday », « jeden Werktag ».
    WeekdayUnit,
    /// Week-end comme unité : « every weekend », « jedes Wochenende ».
    Weekend,
    /// Habitude du week-end : « по выходным », « w weekendy ».
    Weekends,
    And,
    /// Entre le jour et le mois : « 15 de octubre ».
    Of,
    /// Avant un numéro de jour : « le 15 », « the 15th », « el día 15 ».
    DayOfMonth,
    /// Idem, mais le numéro doit porter son suffixe : « the 15th » (« the 3 books » n'est pas une date).
    DayOfMonthOrdinal,
    /// Après un numéro de jour : « 15 числа ».
    DayOfMonthAfter,
    Morning,
    Afternoon,
    Evening,
}

type Table = &'static [(W, &'static str)];

const EN: Table = &[
    (W::Today, "today"),
    (W::Tomorrow, "tomorrow"),
    (W::AfterTomorrow, "day after tomorrow"),
    (W::AfterTomorrow, "the day after tomorrow"),
    (W::Tonight, "tonight"),
    (W::Tonight, "this evening"),
    (W::ThisWeekend, "this weekend"),
    (W::ThisWeekend, "this week-end"),
    (W::NextWeek, "next week"),
    (W::NextMonth, "next month"),
    (W::Next, "next"),
    (W::Next, "this"),
    (W::In, "in"),
    (W::Unit(Unit::Day), "day"),
    (W::Unit(Unit::Day), "days"),
    (W::Unit(Unit::Day), "d"),
    (W::Unit(Unit::Week), "week"),
    (W::Unit(Unit::Week), "weeks"),
    (W::Unit(Unit::Week), "w"),
    (W::Unit(Unit::Month), "month"),
    (W::Unit(Unit::Month), "months"),
    (W::Unit(Unit::Year), "year"),
    (W::Unit(Unit::Year), "years"),
    (W::Unit(Unit::Year), "y"),
    (W::Unit(Unit::Hour), "hour"),
    (W::Unit(Unit::Hour), "hours"),
    (W::Unit(Unit::Hour), "h"),
    (W::Unit(Unit::Hour), "hr"),
    (W::Unit(Unit::Hour), "hrs"),
    (W::Unit(Unit::Minute), "minute"),
    (W::Unit(Unit::Minute), "minutes"),
    (W::Unit(Unit::Minute), "min"),
    (W::Unit(Unit::Minute), "mins"),
    (W::Number(1), "one"),
    (W::Number(1), "a"),
    (W::Number(1), "an"),
    (W::Number(2), "two"),
    (W::Number(3), "three"),
    (W::Number(4), "four"),
    (W::Number(5), "five"),
    (W::Number(6), "six"),
    (W::Number(7), "seven"),
    (W::Number(8), "eight"),
    (W::Number(9), "nine"),
    (W::Number(10), "ten"),
    (W::Weekday(Mon), "monday"),
    (W::Weekday(Tue), "tuesday"),
    (W::Weekday(Wed), "wednesday"),
    (W::Weekday(Thu), "thursday"),
    (W::Weekday(Fri), "friday"),
    (W::Weekday(Sat), "saturday"),
    (W::Weekday(Sun), "sunday"),
    (W::Habitual(Mon), "mondays"),
    (W::Habitual(Tue), "tuesdays"),
    (W::Habitual(Wed), "wednesdays"),
    (W::Habitual(Thu), "thursdays"),
    (W::Habitual(Fri), "fridays"),
    (W::Habitual(Sat), "saturdays"),
    (W::Habitual(Sun), "sundays"),
    (W::Habitual(Mon), "on mondays"),
    (W::Habitual(Tue), "on tuesdays"),
    (W::Habitual(Wed), "on wednesdays"),
    (W::Habitual(Thu), "on thursdays"),
    (W::Habitual(Fri), "on fridays"),
    (W::Habitual(Sat), "on saturdays"),
    (W::Habitual(Sun), "on sundays"),
    (W::Month(1), "january"),
    (W::Month(1), "jan"),
    (W::Month(2), "february"),
    (W::Month(2), "feb"),
    (W::Month(3), "march"),
    (W::Month(3), "mar"),
    (W::Month(4), "april"),
    (W::Month(4), "apr"),
    (W::Month(5), "may"),
    (W::Month(6), "june"),
    (W::Month(6), "jun"),
    (W::Month(7), "july"),
    (W::Month(7), "jul"),
    (W::Month(8), "august"),
    (W::Month(8), "aug"),
    (W::Month(9), "september"),
    (W::Month(9), "sept"),
    (W::Month(9), "sep"),
    (W::Month(10), "october"),
    (W::Month(10), "oct"),
    (W::Month(11), "november"),
    (W::Month(11), "nov"),
    (W::Month(12), "december"),
    (W::Month(12), "dec"),
    (W::Connector, "at"),
    (W::Connector, "on"),
    (W::Connector, "for"),
    (W::Connector, "by"),
    (W::At, "at"),
    (W::HourWord, "o'clock"),
    (W::HourWord, "oclock"),
    (W::Noon, "noon"),
    (W::Noon, "midday"),
    (W::Midnight, "midnight"),
    (W::Am, "am"),
    (W::Am, "a.m"),
    (W::Pm, "pm"),
    (W::Pm, "p.m"),
    (W::Every, "every"),
    (W::Every, "each"),
    (W::Other, "other"),
    (W::Daily, "daily"),
    (W::Weekly, "weekly"),
    (W::Monthly, "monthly"),
    (W::Yearly, "yearly"),
    (W::Yearly, "annually"),
    (W::WeekdaysOnly, "weekdays"),
    (W::WeekdaysOnly, "on weekdays"),
    (W::WeekdayUnit, "weekday"),
    (W::WeekdayUnit, "weekdays"),
    (W::Weekend, "weekend"),
    (W::Weekend, "weekends"),
    (W::Weekend, "week-end"),
    (W::Weekend, "week-ends"),
    (W::Weekends, "on weekends"),
    (W::And, "and"),
    (W::Of, "of"),
    (W::DayOfMonthOrdinal, "the"),
    (W::DayOfMonthOrdinal, "on the"),
    (W::Morning, "morning"),
    (W::Morning, "in the morning"),
    (W::Afternoon, "afternoon"),
    (W::Afternoon, "in the afternoon"),
    (W::Evening, "evening"),
    (W::Evening, "in the evening"),
    (W::Evening, "night"),
];

const FR: Table = &[
    (W::Today, "aujourd'hui"),
    (W::Today, "aujourdhui"),
    (W::Today, "auj"),
    (W::Tomorrow, "demain"),
    (W::AfterTomorrow, "après-demain"),
    (W::AfterTomorrow, "après demain"),
    (W::Tonight, "ce soir"),
    (W::ThisWeekend, "ce week-end"),
    (W::ThisWeekend, "ce weekend"),
    (W::ThisWeekend, "ce we"),
    (W::NextWeek, "semaine prochaine"),
    (W::NextWeek, "la semaine prochaine"),
    (W::NextMonth, "mois prochain"),
    (W::NextMonth, "le mois prochain"),
    (W::NextAfter, "prochain"),
    (W::NextAfter, "prochaine"),
    (W::In, "dans"),
    (W::In, "d'ici"),
    (W::Unit(Unit::Day), "jour"),
    (W::Unit(Unit::Day), "jours"),
    (W::Unit(Unit::Day), "j"),
    (W::Unit(Unit::Week), "semaine"),
    (W::Unit(Unit::Week), "semaines"),
    (W::Unit(Unit::Week), "sem"),
    (W::Unit(Unit::Month), "mois"),
    (W::Unit(Unit::Year), "an"),
    (W::Unit(Unit::Year), "ans"),
    (W::Unit(Unit::Year), "année"),
    (W::Unit(Unit::Year), "années"),
    (W::Unit(Unit::Hour), "heure"),
    (W::Unit(Unit::Hour), "heures"),
    (W::Unit(Unit::Hour), "h"),
    (W::Unit(Unit::Minute), "minute"),
    (W::Unit(Unit::Minute), "minutes"),
    (W::Unit(Unit::Minute), "min"),
    (W::Unit(Unit::Minute), "mins"),
    (W::Number(1), "un"),
    (W::Number(1), "une"),
    (W::Number(2), "deux"),
    (W::Number(3), "trois"),
    (W::Number(4), "quatre"),
    (W::Number(5), "cinq"),
    (W::Number(6), "six"),
    (W::Number(7), "sept"),
    (W::Number(8), "huit"),
    (W::Number(9), "neuf"),
    (W::Number(10), "dix"),
    (W::Weekday(Mon), "lundi"),
    (W::Weekday(Tue), "mardi"),
    (W::Weekday(Wed), "mercredi"),
    (W::Weekday(Thu), "jeudi"),
    (W::Weekday(Fri), "vendredi"),
    (W::Weekday(Sat), "samedi"),
    (W::Weekday(Sun), "dimanche"),
    (W::Weekday(Mon), "lundis"),
    (W::Weekday(Tue), "mardis"),
    (W::Weekday(Wed), "mercredis"),
    (W::Weekday(Thu), "jeudis"),
    (W::Weekday(Fri), "vendredis"),
    (W::Weekday(Sat), "samedis"),
    (W::Weekday(Sun), "dimanches"),
    (W::Habitual(Mon), "les lundis"),
    (W::Habitual(Tue), "les mardis"),
    (W::Habitual(Wed), "les mercredis"),
    (W::Habitual(Thu), "les jeudis"),
    (W::Habitual(Fri), "les vendredis"),
    (W::Habitual(Sat), "les samedis"),
    (W::Habitual(Sun), "les dimanches"),
    (W::Month(1), "janvier"),
    (W::Month(1), "janv"),
    (W::Month(2), "février"),
    (W::Month(2), "févr"),
    (W::Month(2), "fév"),
    (W::Month(3), "mars"),
    (W::Month(4), "avril"),
    (W::Month(4), "avr"),
    (W::Month(5), "mai"),
    (W::Month(6), "juin"),
    (W::Month(7), "juillet"),
    (W::Month(7), "juil"),
    (W::Month(8), "août"),
    (W::Month(9), "septembre"),
    (W::Month(9), "sept"),
    (W::Month(10), "octobre"),
    (W::Month(10), "oct"),
    (W::Month(11), "novembre"),
    (W::Month(11), "nov"),
    (W::Month(12), "décembre"),
    (W::Month(12), "déc"),
    (W::Connector, "à"),
    (W::Connector, "le"),
    (W::Connector, "pour"),
    (W::Connector, "vers"),
    (W::Connector, "avant"),
    (W::Noon, "midi"),
    (W::Midnight, "minuit"),
    (W::Every, "chaque"),
    (W::Every, "tous les"),
    (W::Every, "toutes les"),
    (W::Daily, "quotidien"),
    (W::Daily, "quotidienne"),
    (W::Daily, "quotidiennement"),
    (W::Weekly, "hebdo"),
    (W::Weekly, "hebdomadaire"),
    (W::Monthly, "mensuel"),
    (W::Monthly, "mensuelle"),
    (W::Yearly, "annuel"),
    (W::Yearly, "annuelle"),
    (W::WeekdaysOnly, "en semaine"),
    (W::WeekdayUnit, "jours ouvrés"),
    (W::WeekdayUnit, "jours ouvrables"),
    (W::WeekdayUnit, "jour ouvré"),
    (W::Weekend, "week-end"),
    (W::Weekend, "week-ends"),
    (W::Weekend, "weekend"),
    (W::Weekend, "weekends"),
    (W::And, "et"),
    (W::DayOfMonth, "le"),
    (W::Morning, "matin"),
    (W::Afternoon, "après-midi"),
    (W::Evening, "soir"),
];

const DE: Table = &[
    (W::Today, "heute"),
    (W::Tomorrow, "morgen"),
    (W::AfterTomorrow, "übermorgen"),
    (W::Tonight, "heute abend"),
    (W::Tonight, "heute nacht"),
    (W::ThisWeekend, "am wochenende"),
    (W::ThisWeekend, "dieses wochenende"),
    (W::ThisWeekend, "an diesem wochenende"),
    (W::NextWeek, "nächste woche"),
    (W::NextWeek, "kommende woche"),
    (W::NextMonth, "nächsten monat"),
    (W::NextMonth, "nächster monat"),
    (W::NextMonth, "kommenden monat"),
    (W::NextMonth, "im nächsten monat"),
    (W::Next, "nächsten"),
    (W::Next, "nächster"),
    (W::Next, "nächste"),
    (W::Next, "kommenden"),
    (W::Next, "kommender"),
    (W::Next, "diesen"),
    (W::Next, "am nächsten"),
    (W::Next, "am kommenden"),
    (W::In, "in"),
    (W::Unit(Unit::Day), "tag"),
    (W::Unit(Unit::Day), "tage"),
    (W::Unit(Unit::Day), "tagen"),
    (W::Unit(Unit::Week), "woche"),
    (W::Unit(Unit::Week), "wochen"),
    (W::Unit(Unit::Month), "monat"),
    (W::Unit(Unit::Month), "monate"),
    (W::Unit(Unit::Month), "monaten"),
    (W::Unit(Unit::Year), "jahr"),
    (W::Unit(Unit::Year), "jahre"),
    (W::Unit(Unit::Year), "jahren"),
    (W::Unit(Unit::Hour), "stunde"),
    (W::Unit(Unit::Hour), "stunden"),
    (W::Unit(Unit::Hour), "std"),
    (W::Unit(Unit::Minute), "minute"),
    (W::Unit(Unit::Minute), "minuten"),
    (W::Unit(Unit::Minute), "min"),
    (W::Number(1), "ein"),
    (W::Number(1), "eine"),
    (W::Number(1), "einen"),
    (W::Number(1), "einem"),
    (W::Number(1), "einer"),
    (W::Number(2), "zwei"),
    (W::Number(3), "drei"),
    (W::Number(4), "vier"),
    (W::Number(5), "fünf"),
    (W::Number(6), "sechs"),
    (W::Number(7), "sieben"),
    (W::Number(8), "acht"),
    (W::Number(9), "neun"),
    (W::Number(10), "zehn"),
    (W::Weekday(Mon), "montag"),
    (W::Weekday(Tue), "dienstag"),
    (W::Weekday(Wed), "mittwoch"),
    (W::Weekday(Thu), "donnerstag"),
    (W::Weekday(Fri), "freitag"),
    (W::Weekday(Sat), "samstag"),
    (W::Weekday(Sat), "sonnabend"),
    (W::Weekday(Sun), "sonntag"),
    (W::Habitual(Mon), "montags"),
    (W::Habitual(Tue), "dienstags"),
    (W::Habitual(Wed), "mittwochs"),
    (W::Habitual(Thu), "donnerstags"),
    (W::Habitual(Fri), "freitags"),
    (W::Habitual(Sat), "samstags"),
    (W::Habitual(Sun), "sonntags"),
    (W::Month(1), "januar"),
    (W::Month(1), "jänner"),
    (W::Month(1), "jan"),
    (W::Month(2), "februar"),
    (W::Month(2), "feb"),
    (W::Month(3), "märz"),
    (W::Month(3), "mär"),
    (W::Month(4), "april"),
    (W::Month(4), "apr"),
    (W::Month(5), "mai"),
    (W::Month(6), "juni"),
    (W::Month(6), "jun"),
    (W::Month(7), "juli"),
    (W::Month(7), "jul"),
    (W::Month(8), "august"),
    (W::Month(8), "aug"),
    (W::Month(9), "september"),
    (W::Month(9), "sept"),
    (W::Month(9), "sep"),
    (W::Month(10), "oktober"),
    (W::Month(10), "okt"),
    (W::Month(11), "november"),
    (W::Month(11), "nov"),
    (W::Month(12), "dezember"),
    (W::Month(12), "dez"),
    (W::Connector, "am"),
    (W::Connector, "bis"),
    (W::Connector, "für"),
    (W::At, "um"),
    (W::HourWord, "uhr"),
    (W::Noon, "mittag"),
    (W::Noon, "mittags"),
    (W::Midnight, "mitternacht"),
    (W::Am, "morgens"),
    (W::Am, "früh"),
    (W::Am, "vormittags"),
    (W::Pm, "nachmittags"),
    (W::Pm, "abends"),
    (W::Every, "jeden"),
    (W::Every, "jede"),
    (W::Every, "jedes"),
    (W::Every, "alle"),
    (W::Other, "zweite"),
    (W::Daily, "täglich"),
    (W::Weekly, "wöchentlich"),
    (W::Monthly, "monatlich"),
    (W::Yearly, "jährlich"),
    (W::WeekdaysOnly, "werktags"),
    (W::WeekdaysOnly, "wochentags"),
    (W::WeekdaysOnly, "an werktagen"),
    (W::WeekdayUnit, "werktag"),
    (W::Weekend, "wochenende"),
    (W::Weekend, "wochenenden"),
    (W::And, "und"),
    (W::DayOfMonth, "am"),
    (W::DayOfMonth, "den"),
    (W::Morning, "morgens"),
    (W::Morning, "früh"),
    (W::Morning, "vormittag"),
    (W::Afternoon, "nachmittag"),
    (W::Afternoon, "nachmittags"),
    (W::Evening, "abend"),
    (W::Evening, "abends"),
];

const ES: Table = &[
    (W::Today, "hoy"),
    (W::Tomorrow, "mañana"),
    (W::AfterTomorrow, "pasado mañana"),
    (W::Tonight, "esta noche"),
    (W::Tonight, "hoy por la noche"),
    (W::ThisWeekend, "este fin de semana"),
    (W::ThisWeekend, "el fin de semana"),
    (W::NextWeek, "la próxima semana"),
    (W::NextWeek, "la semana que viene"),
    (W::NextWeek, "próxima semana"),
    (W::NextWeek, "semana que viene"),
    (W::NextMonth, "el próximo mes"),
    (W::NextMonth, "el mes que viene"),
    (W::NextMonth, "próximo mes"),
    (W::NextMonth, "mes que viene"),
    (W::Next, "próximo"),
    (W::Next, "próxima"),
    (W::Next, "el próximo"),
    (W::NextAfter, "que viene"),
    (W::In, "en"),
    (W::In, "dentro de"),
    (W::Unit(Unit::Day), "día"),
    (W::Unit(Unit::Day), "días"),
    (W::Unit(Unit::Week), "semana"),
    (W::Unit(Unit::Week), "semanas"),
    (W::Unit(Unit::Month), "mes"),
    (W::Unit(Unit::Month), "meses"),
    (W::Unit(Unit::Year), "año"),
    (W::Unit(Unit::Year), "años"),
    (W::Unit(Unit::Hour), "hora"),
    (W::Unit(Unit::Hour), "horas"),
    (W::Unit(Unit::Minute), "minuto"),
    (W::Unit(Unit::Minute), "minutos"),
    (W::Unit(Unit::Minute), "min"),
    (W::Number(1), "un"),
    (W::Number(1), "uno"),
    (W::Number(1), "una"),
    (W::Number(2), "dos"),
    (W::Number(3), "tres"),
    (W::Number(4), "cuatro"),
    (W::Number(5), "cinco"),
    (W::Number(6), "seis"),
    (W::Number(7), "siete"),
    (W::Number(8), "ocho"),
    (W::Number(9), "nueve"),
    (W::Number(10), "diez"),
    (W::Weekday(Mon), "lunes"),
    (W::Weekday(Tue), "martes"),
    (W::Weekday(Wed), "miércoles"),
    (W::Weekday(Thu), "jueves"),
    (W::Weekday(Fri), "viernes"),
    (W::Weekday(Sat), "sábado"),
    (W::Weekday(Sat), "sábados"),
    (W::Weekday(Sun), "domingo"),
    (W::Weekday(Sun), "domingos"),
    (W::Habitual(Mon), "los lunes"),
    (W::Habitual(Tue), "los martes"),
    (W::Habitual(Wed), "los miércoles"),
    (W::Habitual(Thu), "los jueves"),
    (W::Habitual(Fri), "los viernes"),
    (W::Habitual(Sat), "los sábados"),
    (W::Habitual(Sun), "los domingos"),
    (W::Month(1), "enero"),
    (W::Month(1), "ene"),
    (W::Month(2), "febrero"),
    (W::Month(2), "feb"),
    (W::Month(3), "marzo"),
    (W::Month(3), "mar"),
    (W::Month(4), "abril"),
    (W::Month(4), "abr"),
    (W::Month(5), "mayo"),
    (W::Month(5), "may"),
    (W::Month(6), "junio"),
    (W::Month(6), "jun"),
    (W::Month(7), "julio"),
    (W::Month(7), "jul"),
    (W::Month(8), "agosto"),
    (W::Month(8), "ago"),
    (W::Month(9), "septiembre"),
    (W::Month(9), "setiembre"),
    (W::Month(9), "sept"),
    (W::Month(9), "sep"),
    (W::Month(10), "octubre"),
    (W::Month(10), "oct"),
    (W::Month(11), "noviembre"),
    (W::Month(11), "nov"),
    (W::Month(12), "diciembre"),
    (W::Month(12), "dic"),
    (W::Connector, "el"),
    (W::Connector, "para"),
    (W::At, "a las"),
    (W::At, "a la"),
    (W::HourWord, "horas"),
    (W::Noon, "mediodía"),
    (W::Noon, "al mediodía"),
    (W::Midnight, "medianoche"),
    (W::Am, "de la mañana"),
    (W::Pm, "de la tarde"),
    (W::Pm, "de la noche"),
    (W::Half, "y media"),
    (W::Every, "cada"),
    (W::Every, "todos los"),
    (W::Every, "todas las"),
    (W::Daily, "diario"),
    (W::Daily, "diariamente"),
    (W::Daily, "a diario"),
    (W::Weekly, "semanal"),
    (W::Weekly, "semanalmente"),
    (W::Monthly, "mensual"),
    (W::Monthly, "mensualmente"),
    (W::Yearly, "anual"),
    (W::Yearly, "anualmente"),
    (W::WeekdaysOnly, "entre semana"),
    (W::WeekdaysOnly, "de lunes a viernes"),
    (W::WeekdaysOnly, "los días laborables"),
    (W::WeekdayUnit, "día laborable"),
    (W::WeekdayUnit, "días laborables"),
    (W::Weekend, "fin de semana"),
    (W::Weekend, "fines de semana"),
    (W::Weekends, "los fines de semana"),
    (W::And, "y"),
    (W::And, "e"),
    (W::Of, "de"),
    (W::DayOfMonth, "el"),
    (W::DayOfMonth, "el día"),
    (W::DayOfMonth, "día"),
    (W::Morning, "por la mañana"),
    (W::Afternoon, "por la tarde"),
    (W::Evening, "por la noche"),
];

const IT: Table = &[
    (W::Today, "oggi"),
    (W::Tomorrow, "domani"),
    (W::AfterTomorrow, "dopodomani"),
    (W::AfterTomorrow, "dopo domani"),
    (W::Tonight, "stasera"),
    (W::Tonight, "questa sera"),
    (W::Tonight, "stanotte"),
    (W::ThisWeekend, "questo fine settimana"),
    (W::ThisWeekend, "questo weekend"),
    (W::ThisWeekend, "nel fine settimana"),
    (W::ThisWeekend, "nel weekend"),
    (W::NextWeek, "la prossima settimana"),
    (W::NextWeek, "prossima settimana"),
    (W::NextWeek, "la settimana prossima"),
    (W::NextWeek, "settimana prossima"),
    (W::NextMonth, "il prossimo mese"),
    (W::NextMonth, "prossimo mese"),
    (W::NextMonth, "il mese prossimo"),
    (W::NextMonth, "mese prossimo"),
    (W::Next, "prossimo"),
    (W::Next, "prossima"),
    (W::Next, "il prossimo"),
    (W::Next, "la prossima"),
    (W::NextAfter, "prossimo"),
    (W::NextAfter, "prossima"),
    (W::In, "tra"),
    (W::In, "fra"),
    (W::Unit(Unit::Day), "giorno"),
    (W::Unit(Unit::Day), "giorni"),
    (W::Unit(Unit::Week), "settimana"),
    (W::Unit(Unit::Week), "settimane"),
    (W::Unit(Unit::Month), "mese"),
    (W::Unit(Unit::Month), "mesi"),
    (W::Unit(Unit::Year), "anno"),
    (W::Unit(Unit::Year), "anni"),
    (W::Unit(Unit::Hour), "ora"),
    (W::Unit(Unit::Hour), "ore"),
    (W::Unit(Unit::Minute), "minuto"),
    (W::Unit(Unit::Minute), "minuti"),
    (W::Unit(Unit::Minute), "min"),
    (W::Number(1), "un"),
    (W::Number(1), "uno"),
    (W::Number(1), "una"),
    (W::Number(2), "due"),
    (W::Number(3), "tre"),
    (W::Number(4), "quattro"),
    (W::Number(5), "cinque"),
    (W::Number(6), "sei"),
    (W::Number(7), "sette"),
    (W::Number(8), "otto"),
    (W::Number(9), "nove"),
    (W::Number(10), "dieci"),
    (W::Weekday(Mon), "lunedì"),
    (W::Weekday(Tue), "martedì"),
    (W::Weekday(Wed), "mercoledì"),
    (W::Weekday(Thu), "giovedì"),
    (W::Weekday(Fri), "venerdì"),
    (W::Weekday(Sat), "sabato"),
    (W::Weekday(Sun), "domenica"),
    (W::Month(1), "gennaio"),
    (W::Month(1), "gen"),
    (W::Month(2), "febbraio"),
    (W::Month(2), "feb"),
    (W::Month(3), "marzo"),
    (W::Month(3), "mar"),
    (W::Month(4), "aprile"),
    (W::Month(4), "apr"),
    (W::Month(5), "maggio"),
    (W::Month(5), "mag"),
    (W::Month(6), "giugno"),
    (W::Month(6), "giu"),
    (W::Month(7), "luglio"),
    (W::Month(7), "lug"),
    (W::Month(8), "agosto"),
    (W::Month(8), "ago"),
    (W::Month(9), "settembre"),
    (W::Month(9), "set"),
    (W::Month(10), "ottobre"),
    (W::Month(10), "ott"),
    (W::Month(11), "novembre"),
    (W::Month(11), "nov"),
    (W::Month(12), "dicembre"),
    (W::Month(12), "dic"),
    (W::Connector, "il"),
    (W::Connector, "per"),
    (W::Connector, "entro"),
    (W::At, "alle"),
    (W::At, "alle ore"),
    (W::Noon, "mezzogiorno"),
    (W::Noon, "a mezzogiorno"),
    (W::Midnight, "mezzanotte"),
    (W::Am, "di mattina"),
    (W::Am, "del mattino"),
    (W::Pm, "di pomeriggio"),
    (W::Pm, "del pomeriggio"),
    (W::Pm, "di sera"),
    (W::Half, "e mezza"),
    (W::Half, "e mezzo"),
    (W::Every, "ogni"),
    (W::Every, "tutti i"),
    (W::Every, "tutte le"),
    (W::Daily, "quotidianamente"),
    (W::Daily, "giornalmente"),
    (W::Weekly, "settimanalmente"),
    (W::Weekly, "settimanale"),
    (W::Monthly, "mensilmente"),
    (W::Monthly, "mensile"),
    (W::Yearly, "annualmente"),
    (W::Yearly, "annuale"),
    (W::WeekdaysOnly, "nei giorni feriali"),
    (W::WeekdaysOnly, "dal lunedì al venerdì"),
    (W::WeekdayUnit, "giorno feriale"),
    (W::WeekdayUnit, "giorni feriali"),
    (W::Weekend, "fine settimana"),
    (W::Weekend, "weekend"),
    (W::And, "e"),
    (W::And, "ed"),
    (W::DayOfMonth, "il"),
    (W::Morning, "mattina"),
    (W::Morning, "di mattina"),
    (W::Morning, "in mattinata"),
    (W::Afternoon, "pomeriggio"),
    (W::Afternoon, "nel pomeriggio"),
    (W::Evening, "sera"),
    (W::Evening, "di sera"),
    (W::Evening, "in serata"),
];

const PT_BR: Table = &[
    (W::Today, "hoje"),
    (W::Tomorrow, "amanhã"),
    (W::AfterTomorrow, "depois de amanhã"),
    (W::Tonight, "hoje à noite"),
    (W::Tonight, "hoje de noite"),
    (W::Tonight, "esta noite"),
    (W::ThisWeekend, "este fim de semana"),
    (W::ThisWeekend, "neste fim de semana"),
    (W::ThisWeekend, "esse fim de semana"),
    (W::ThisWeekend, "nesse fim de semana"),
    (W::ThisWeekend, "no fim de semana"),
    (W::NextWeek, "semana que vem"),
    (W::NextWeek, "na semana que vem"),
    (W::NextWeek, "próxima semana"),
    (W::NextWeek, "na próxima semana"),
    (W::NextMonth, "mês que vem"),
    (W::NextMonth, "no mês que vem"),
    (W::NextMonth, "próximo mês"),
    (W::NextMonth, "no próximo mês"),
    (W::Next, "próxima"),
    (W::Next, "próximo"),
    (W::Next, "na próxima"),
    (W::Next, "no próximo"),
    (W::NextAfter, "que vem"),
    (W::In, "em"),
    (W::In, "daqui a"),
    (W::In, "dentro de"),
    (W::Unit(Unit::Day), "dia"),
    (W::Unit(Unit::Day), "dias"),
    (W::Unit(Unit::Week), "semana"),
    (W::Unit(Unit::Week), "semanas"),
    (W::Unit(Unit::Month), "mês"),
    (W::Unit(Unit::Month), "meses"),
    (W::Unit(Unit::Year), "ano"),
    (W::Unit(Unit::Year), "anos"),
    (W::Unit(Unit::Hour), "hora"),
    (W::Unit(Unit::Hour), "horas"),
    (W::Unit(Unit::Minute), "minuto"),
    (W::Unit(Unit::Minute), "minutos"),
    (W::Unit(Unit::Minute), "min"),
    (W::Number(1), "um"),
    (W::Number(1), "uma"),
    (W::Number(2), "dois"),
    (W::Number(2), "duas"),
    (W::Number(3), "três"),
    (W::Number(4), "quatro"),
    (W::Number(5), "cinco"),
    (W::Number(6), "seis"),
    (W::Number(7), "sete"),
    (W::Number(8), "oito"),
    (W::Number(9), "nove"),
    (W::Number(10), "dez"),
    (W::Weekday(Mon), "segunda-feira"),
    (W::Weekday(Tue), "terça-feira"),
    (W::Weekday(Wed), "quarta-feira"),
    (W::Weekday(Thu), "quinta-feira"),
    (W::Weekday(Fri), "sexta-feira"),
    (W::Weekday(Mon), "segundas-feiras"),
    (W::Weekday(Tue), "terças-feiras"),
    (W::Weekday(Wed), "quartas-feiras"),
    (W::Weekday(Thu), "quintas-feiras"),
    (W::Weekday(Fri), "sextas-feiras"),
    (W::Weekday(Sat), "sábado"),
    (W::Weekday(Sat), "sábados"),
    (W::Weekday(Sun), "domingo"),
    (W::Weekday(Sun), "domingos"),
    (W::WeakWeekday(Mon), "segunda"),
    (W::WeakWeekday(Tue), "terça"),
    (W::WeakWeekday(Wed), "quarta"),
    (W::WeakWeekday(Thu), "quinta"),
    (W::WeakWeekday(Fri), "sexta"),
    (W::WeakWeekday(Mon), "segundas"),
    (W::WeakWeekday(Tue), "terças"),
    (W::WeakWeekday(Wed), "quartas"),
    (W::WeakWeekday(Thu), "quintas"),
    (W::WeakWeekday(Fri), "sextas"),
    (W::Habitual(Mon), "às segundas"),
    (W::Habitual(Tue), "às terças"),
    (W::Habitual(Wed), "às quartas"),
    (W::Habitual(Thu), "às quintas"),
    (W::Habitual(Fri), "às sextas"),
    (W::Habitual(Mon), "às segundas-feiras"),
    (W::Habitual(Tue), "às terças-feiras"),
    (W::Habitual(Wed), "às quartas-feiras"),
    (W::Habitual(Thu), "às quintas-feiras"),
    (W::Habitual(Fri), "às sextas-feiras"),
    (W::Habitual(Sat), "aos sábados"),
    (W::Habitual(Sun), "aos domingos"),
    (W::Month(1), "janeiro"),
    (W::Month(1), "jan"),
    (W::Month(2), "fevereiro"),
    (W::Month(2), "fev"),
    (W::Month(3), "março"),
    (W::Month(3), "mar"),
    (W::Month(4), "abril"),
    (W::Month(4), "abr"),
    (W::Month(5), "maio"),
    (W::Month(5), "mai"),
    (W::Month(6), "junho"),
    (W::Month(6), "jun"),
    (W::Month(7), "julho"),
    (W::Month(7), "jul"),
    (W::Month(8), "agosto"),
    (W::Month(8), "ago"),
    (W::Month(9), "setembro"),
    (W::Month(9), "set"),
    (W::Month(10), "outubro"),
    (W::Month(10), "out"),
    (W::Month(11), "novembro"),
    (W::Month(11), "nov"),
    (W::Month(12), "dezembro"),
    (W::Month(12), "dez"),
    (W::Connector, "na"),
    (W::Connector, "no"),
    (W::Connector, "até"),
    (W::Connector, "para"),
    (W::Connector, "em"),
    (W::At, "às"),
    (W::HourWord, "horas"),
    (W::Noon, "meio-dia"),
    (W::Noon, "meio dia"),
    (W::Midnight, "meia-noite"),
    (W::Am, "da manhã"),
    (W::Pm, "da tarde"),
    (W::Pm, "da noite"),
    (W::Half, "e meia"),
    (W::Every, "cada"),
    (W::Every, "a cada"),
    (W::Every, "todo"),
    (W::Every, "toda"),
    (W::Every, "todos os"),
    (W::Every, "todas as"),
    (W::Daily, "diariamente"),
    (W::Weekly, "semanalmente"),
    (W::Monthly, "mensalmente"),
    (W::Yearly, "anualmente"),
    (W::WeekdaysOnly, "dias úteis"),
    (W::WeekdaysOnly, "nos dias úteis"),
    (W::WeekdaysOnly, "de segunda a sexta"),
    (W::WeekdayUnit, "dia útil"),
    (W::WeekdayUnit, "dias úteis"),
    (W::Weekend, "fim de semana"),
    (W::Weekend, "fins de semana"),
    (W::Weekends, "aos fins de semana"),
    (W::And, "e"),
    (W::Of, "de"),
    (W::DayOfMonth, "dia"),
    (W::DayOfMonth, "no dia"),
    (W::Morning, "de manhã"),
    (W::Morning, "pela manhã"),
    (W::Afternoon, "à tarde"),
    (W::Afternoon, "de tarde"),
    (W::Evening, "à noite"),
    (W::Evening, "de noite"),
];

const RU: Table = &[
    (W::Today, "сегодня"),
    (W::Tomorrow, "завтра"),
    (W::AfterTomorrow, "послезавтра"),
    (W::Tonight, "сегодня вечером"),
    (W::ThisWeekend, "в эти выходные"),
    (W::ThisWeekend, "на выходных"),
    (W::ThisWeekend, "на этих выходных"),
    (W::NextWeek, "на следующей неделе"),
    (W::NextWeek, "на будущей неделе"),
    (W::NextMonth, "в следующем месяце"),
    (W::NextMonth, "в будущем месяце"),
    (W::Next, "в следующий"),
    (W::Next, "в следующую"),
    (W::Next, "в следующее"),
    (W::Next, "следующий"),
    (W::Next, "следующую"),
    (W::In, "через"),
    (W::Unit(Unit::Day), "день"),
    (W::Unit(Unit::Day), "дня"),
    (W::Unit(Unit::Day), "дней"),
    (W::Unit(Unit::Week), "неделю"),
    (W::Unit(Unit::Week), "недели"),
    (W::Unit(Unit::Week), "недель"),
    (W::Unit(Unit::Week), "неделя"),
    (W::Unit(Unit::Month), "месяц"),
    (W::Unit(Unit::Month), "месяца"),
    (W::Unit(Unit::Month), "месяцев"),
    (W::Unit(Unit::Year), "год"),
    (W::Unit(Unit::Year), "года"),
    (W::Unit(Unit::Year), "лет"),
    (W::Unit(Unit::Hour), "час"),
    (W::Unit(Unit::Hour), "часа"),
    (W::Unit(Unit::Hour), "часов"),
    (W::Unit(Unit::Hour), "ч"),
    (W::Unit(Unit::Minute), "минуту"),
    (W::Unit(Unit::Minute), "минуты"),
    (W::Unit(Unit::Minute), "минут"),
    (W::Unit(Unit::Minute), "мин"),
    (W::Number(1), "один"),
    (W::Number(1), "одну"),
    (W::Number(1), "одна"),
    (W::Number(2), "два"),
    (W::Number(2), "две"),
    (W::Number(3), "три"),
    (W::Number(4), "четыре"),
    (W::Number(5), "пять"),
    (W::Number(6), "шесть"),
    (W::Number(7), "семь"),
    (W::Number(8), "восемь"),
    (W::Number(9), "девять"),
    (W::Number(10), "десять"),
    (W::Weekday(Mon), "понедельник"),
    (W::Weekday(Tue), "вторник"),
    (W::Weekday(Wed), "среда"),
    (W::Weekday(Wed), "среду"),
    (W::Weekday(Thu), "четверг"),
    (W::Weekday(Fri), "пятница"),
    (W::Weekday(Fri), "пятницу"),
    (W::Weekday(Sat), "суббота"),
    (W::Weekday(Sat), "субботу"),
    (W::Weekday(Sun), "воскресенье"),
    (W::Weekday(Mon), "понедельникам"),
    (W::Weekday(Tue), "вторникам"),
    (W::Weekday(Wed), "средам"),
    (W::Weekday(Thu), "четвергам"),
    (W::Weekday(Fri), "пятницам"),
    (W::Weekday(Sat), "субботам"),
    (W::Weekday(Sun), "воскресеньям"),
    (W::Habitual(Mon), "по понедельникам"),
    (W::Habitual(Tue), "по вторникам"),
    (W::Habitual(Wed), "по средам"),
    (W::Habitual(Thu), "по четвергам"),
    (W::Habitual(Fri), "по пятницам"),
    (W::Habitual(Sat), "по субботам"),
    (W::Habitual(Sun), "по воскресеньям"),
    (W::Month(1), "январь"),
    (W::Month(1), "января"),
    (W::Month(1), "янв"),
    (W::Month(2), "февраль"),
    (W::Month(2), "февраля"),
    (W::Month(2), "февр"),
    (W::Month(2), "фев"),
    (W::Month(3), "март"),
    (W::Month(3), "марта"),
    (W::Month(3), "мар"),
    (W::Month(4), "апрель"),
    (W::Month(4), "апреля"),
    (W::Month(4), "апр"),
    (W::Month(5), "май"),
    (W::Month(5), "мая"),
    (W::Month(6), "июнь"),
    (W::Month(6), "июня"),
    (W::Month(6), "июн"),
    (W::Month(7), "июль"),
    (W::Month(7), "июля"),
    (W::Month(7), "июл"),
    (W::Month(8), "август"),
    (W::Month(8), "августа"),
    (W::Month(8), "авг"),
    (W::Month(9), "сентябрь"),
    (W::Month(9), "сентября"),
    (W::Month(9), "сент"),
    (W::Month(9), "сен"),
    (W::Month(10), "октябрь"),
    (W::Month(10), "октября"),
    (W::Month(10), "окт"),
    (W::Month(11), "ноябрь"),
    (W::Month(11), "ноября"),
    (W::Month(11), "нояб"),
    (W::Month(11), "ноя"),
    (W::Month(12), "декабрь"),
    (W::Month(12), "декабря"),
    (W::Month(12), "дек"),
    (W::Connector, "в"),
    (W::Connector, "во"),
    (W::Connector, "к"),
    (W::Connector, "до"),
    (W::Connector, "на"),
    (W::At, "в"),
    (W::At, "во"),
    (W::HourWord, "час"),
    (W::HourWord, "часа"),
    (W::HourWord, "часов"),
    (W::Noon, "полдень"),
    (W::Noon, "в полдень"),
    (W::Midnight, "полночь"),
    (W::Midnight, "в полночь"),
    (W::Am, "утра"),
    (W::Pm, "дня"),
    (W::Pm, "вечера"),
    (W::Every, "каждый"),
    (W::Every, "каждую"),
    (W::Every, "каждое"),
    (W::Every, "каждые"),
    (W::Daily, "ежедневно"),
    (W::Weekly, "еженедельно"),
    (W::Monthly, "ежемесячно"),
    (W::Yearly, "ежегодно"),
    (W::WeekdaysOnly, "по будням"),
    (W::WeekdaysOnly, "в будни"),
    (W::WeekdaysOnly, "по рабочим дням"),
    (W::WeekdayUnit, "будний день"),
    (W::WeekdayUnit, "рабочий день"),
    (W::Weekend, "выходные"),
    (W::Weekends, "по выходным"),
    (W::And, "и"),
    (W::DayOfMonthAfter, "числа"),
    (W::Morning, "утром"),
    (W::Afternoon, "днём"),
    (W::Evening, "вечером"),
];

const PL: Table = &[
    (W::Today, "dziś"),
    (W::Today, "dzisiaj"),
    (W::Tomorrow, "jutro"),
    (W::AfterTomorrow, "pojutrze"),
    (W::Tonight, "dziś wieczorem"),
    (W::Tonight, "dzisiaj wieczorem"),
    (W::ThisWeekend, "w ten weekend"),
    (W::ThisWeekend, "w weekend"),
    (W::ThisWeekend, "w najbliższy weekend"),
    (W::NextWeek, "w przyszłym tygodniu"),
    (W::NextWeek, "w następnym tygodniu"),
    (W::NextMonth, "w przyszłym miesiącu"),
    (W::NextMonth, "w następnym miesiącu"),
    (W::Next, "w przyszły"),
    (W::Next, "w przyszłą"),
    (W::Next, "w przyszłe"),
    (W::Next, "w następny"),
    (W::Next, "w następną"),
    (W::Next, "przyszły"),
    (W::Next, "przyszłą"),
    (W::In, "za"),
    (W::Unit(Unit::Day), "dzień"),
    (W::Unit(Unit::Day), "dni"),
    (W::Unit(Unit::Day), "dnia"),
    (W::Unit(Unit::Week), "tydzień"),
    (W::Unit(Unit::Week), "tygodnie"),
    (W::Unit(Unit::Week), "tygodni"),
    (W::Unit(Unit::Week), "tygodnia"),
    (W::Unit(Unit::Month), "miesiąc"),
    (W::Unit(Unit::Month), "miesiące"),
    (W::Unit(Unit::Month), "miesięcy"),
    (W::Unit(Unit::Month), "miesiąca"),
    (W::Unit(Unit::Year), "rok"),
    (W::Unit(Unit::Year), "lata"),
    (W::Unit(Unit::Year), "lat"),
    (W::Unit(Unit::Year), "roku"),
    (W::Unit(Unit::Hour), "godzinę"),
    (W::Unit(Unit::Hour), "godziny"),
    (W::Unit(Unit::Hour), "godzin"),
    (W::Unit(Unit::Hour), "godz"),
    (W::Unit(Unit::Minute), "minutę"),
    (W::Unit(Unit::Minute), "minuty"),
    (W::Unit(Unit::Minute), "minut"),
    (W::Unit(Unit::Minute), "min"),
    (W::Number(1), "jeden"),
    (W::Number(1), "jedną"),
    (W::Number(1), "jedna"),
    (W::Number(2), "dwa"),
    (W::Number(2), "dwie"),
    (W::Number(3), "trzy"),
    (W::Number(4), "cztery"),
    (W::Number(5), "pięć"),
    (W::Number(6), "sześć"),
    (W::Number(7), "siedem"),
    (W::Number(8), "osiem"),
    (W::Number(9), "dziewięć"),
    (W::Number(10), "dziesięć"),
    (W::Weekday(Mon), "poniedziałek"),
    (W::Weekday(Tue), "wtorek"),
    (W::Weekday(Wed), "środa"),
    (W::Weekday(Wed), "środę"),
    (W::Weekday(Thu), "czwartek"),
    (W::Weekday(Fri), "piątek"),
    (W::Weekday(Sat), "sobota"),
    (W::Weekday(Sat), "sobotę"),
    (W::Weekday(Sun), "niedziela"),
    (W::Weekday(Sun), "niedzielę"),
    (W::Weekday(Mon), "poniedziałki"),
    (W::Weekday(Tue), "wtorki"),
    (W::Weekday(Wed), "środy"),
    (W::Weekday(Thu), "czwartki"),
    (W::Weekday(Fri), "piątki"),
    (W::Weekday(Sat), "soboty"),
    (W::Weekday(Sun), "niedziele"),
    (W::Habitual(Mon), "w poniedziałki"),
    (W::Habitual(Tue), "we wtorki"),
    (W::Habitual(Wed), "w środy"),
    (W::Habitual(Thu), "w czwartki"),
    (W::Habitual(Fri), "w piątki"),
    (W::Habitual(Sat), "w soboty"),
    (W::Habitual(Sun), "w niedziele"),
    (W::Month(1), "styczeń"),
    (W::Month(1), "stycznia"),
    (W::Month(1), "sty"),
    (W::Month(2), "luty"),
    (W::Month(2), "lutego"),
    (W::Month(2), "lut"),
    (W::Month(3), "marzec"),
    (W::Month(3), "marca"),
    (W::Month(3), "mar"),
    (W::Month(4), "kwiecień"),
    (W::Month(4), "kwietnia"),
    (W::Month(4), "kwi"),
    (W::Month(5), "maj"),
    (W::Month(5), "maja"),
    (W::Month(6), "czerwiec"),
    (W::Month(6), "czerwca"),
    (W::Month(6), "cze"),
    (W::Month(7), "lipiec"),
    (W::Month(7), "lipca"),
    (W::Month(7), "lip"),
    (W::Month(8), "sierpień"),
    (W::Month(8), "sierpnia"),
    (W::Month(8), "sie"),
    (W::Month(9), "wrzesień"),
    (W::Month(9), "września"),
    (W::Month(9), "wrz"),
    (W::Month(10), "październik"),
    (W::Month(10), "października"),
    (W::Month(10), "paź"),
    (W::Month(11), "listopad"),
    (W::Month(11), "listopada"),
    (W::Month(11), "lis"),
    (W::Month(12), "grudzień"),
    (W::Month(12), "grudnia"),
    (W::Month(12), "gru"),
    (W::Connector, "w"),
    (W::Connector, "we"),
    (W::Connector, "na"),
    (W::Connector, "do"),
    (W::At, "o"),
    (W::At, "o godzinie"),
    (W::HourWord, "godz"),
    (W::Noon, "południe"),
    (W::Noon, "w południe"),
    (W::Midnight, "północ"),
    (W::Midnight, "o północy"),
    (W::Am, "rano"),
    (W::Pm, "po południu"),
    (W::Pm, "wieczorem"),
    (W::Every, "co"),
    (W::Every, "każdy"),
    (W::Every, "każdą"),
    (W::Every, "każde"),
    (W::Every, "każdego"),
    (W::Every, "w każdy"),
    (W::Every, "w każdą"),
    (W::Daily, "codziennie"),
    (W::Weekly, "cotygodniowo"),
    (W::Monthly, "comiesięcznie"),
    (W::Yearly, "corocznie"),
    (W::WeekdaysOnly, "w dni robocze"),
    (W::WeekdaysOnly, "w dni powszednie"),
    (W::WeekdayUnit, "dzień roboczy"),
    (W::Weekend, "weekend"),
    (W::Weekends, "w weekendy"),
    (W::And, "i"),
    (W::And, "oraz"),
    (W::Morning, "rano"),
    (W::Afternoon, "po południu"),
    (W::Evening, "wieczorem"),
];

/// Langues à alphabet latin qui ne s'activent qu'en langue d'interface.
const BY_INTERFACE: &[(&str, Table)] = &[("de", DE), ("es", ES), ("it", IT), ("pt_BR", PT_BR), ("pl", PL)];

/// Formes actives, indexées par leur premier mot (sans casse ni accents).
pub struct Lexicon {
    by_first: HashMap<String, Vec<(Vec<String>, W)>>,
}

impl Lexicon {
    fn build(tables: &[Table]) -> Lexicon {
        let mut by_first: HashMap<String, Vec<(Vec<String>, W)>> = HashMap::new();
        for (meaning, phrase) in tables.iter().flat_map(|t| t.iter()) {
            let words: Vec<String> = fold(phrase).split_whitespace().map(String::from).collect();
            by_first.entry(words[0].clone()).or_default().push((words, *meaning));
        }
        // Les locutions les plus longues d'abord : « la semaine prochaine » avant « la ».
        for entries in by_first.values_mut() {
            entries.sort_by_key(|(words, _)| std::cmp::Reverse(words.len()));
        }
        Lexicon { by_first }
    }

    /// Lexique pour la langue d'interface `code`.
    pub fn for_language(code: &str) -> &'static Lexicon {
        static CACHE: OnceLock<Mutex<HashMap<String, &'static Lexicon>>> = OnceLock::new();
        let mut cache = CACHE.get_or_init(Default::default).lock().unwrap_or_else(|e| e.into_inner());
        cache.entry(code.to_string()).or_insert_with(|| {
            let mut tables = vec![EN, FR, RU];
            tables.extend(BY_INTERFACE.iter().filter(|(c, _)| *c == code).map(|(_, t)| *t));
            Box::leak(Box::new(Lexicon::build(&tables)))
        })
    }

    /// Sens reconnus à partir de `words[0]`, avec leur longueur en mots, les plus longs d'abord.
    pub fn at<'a>(&'a self, words: &'a [&'a str]) -> impl Iterator<Item = (W, usize)> + 'a {
        let entries = words.first().and_then(|first| self.by_first.get(*first));
        entries.into_iter().flatten().filter_map(move |(phrase, meaning)| {
            (words.len() >= phrase.len() && phrase.iter().zip(words).all(|(p, w)| p == w))
                .then_some((*meaning, phrase.len()))
        })
    }
}
